from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from stock_content.domain.artifacts import ArtifactBase
from stock_content.domain.claims import FinancialClaim
from stock_content.domain.models import (
    ContentTask,
    KnowledgeUnit,
    TranscriptSegment,
    VideoAsset,
    VideoChapter,
    VideoSummary,
)


class KnowledgeRepository(Protocol):
    def get(self, knowledge_uid: str) -> dict | None: ...

    def list_for_video(self, video_id: str, limit: int) -> list[dict]: ...

    def search(self, query: str, filters: dict, limit: int) -> list[dict]: ...

    def replace_for_video(self, video_id: str, units: list[KnowledgeUnit]) -> None: ...

    def hydrate(self, knowledge_uids: list[str], filters: dict) -> list[dict]: ...

    def factor_signals(
        self,
        symbols: list[str],
        start: datetime,
        end: datetime,
        minimum_support_status: str,
    ) -> list[dict]: ...


class ContentTaskRepository(Protocol):
    def create(self, task: ContentTask) -> ContentTask: ...

    def get(self, task_id: str) -> ContentTask | None: ...

    def claim_pending(self, worker_id: str, lease_seconds: int) -> ContentTask | None: ...

    def update_progress(self, task_id: str, stage: str, progress: int) -> None: ...

    def checkpoint(self, task_id: str, stage: str, checkpoint: dict, progress: int | None = None) -> None: ...

    def succeed(self, task_id: str, result: dict[str, Any]) -> None: ...

    def fail(self, task_id: str, stage: str, error: str) -> None: ...


class VideoRepository(Protocol):
    def upsert(self, video: VideoAsset, segments: list[TranscriptSegment]) -> None: ...

    def get(self, video_id: str) -> dict | None: ...

    def list(self, limit: int) -> list[dict]: ...


class ChapterRepository(Protocol):
    def replace_for_video(self, video_id: str, chapters: list[VideoChapter]) -> None: ...

    def list_for_video(self, video_id: str) -> list[dict]: ...


class SummaryRepository(Protocol):
    def upsert(self, summary: VideoSummary) -> None: ...

    def get(self, video_id: str) -> dict | None: ...


class KnowledgeIndex(Protocol):
    def index(self, units: list[KnowledgeUnit]) -> None: ...

    def search(self, query: str, limit: int) -> list[str]: ...


class MultimodalRepository(Protocol):
    def replace(
        self, video_id: str, frames: list[dict], ocr: list[dict], vision: list[dict], windows: list[dict]
    ) -> None: ...
    def list_frames(self, video_id: str) -> list[dict]: ...
    def list_ocr(self, video_id: str) -> list[dict]: ...
    def list_vision(self, video_id: str) -> list[dict]: ...
    def list_temporal_windows(self, video_id: str) -> list[dict]: ...


class ArtifactRepository(Protocol):
    def put(self, artifact: ArtifactBase) -> ArtifactBase: ...
    def get(self, artifact_id: str) -> ArtifactBase | None: ...
    def get_many(self, artifact_ids: list[str]) -> list[ArtifactBase]: ...
    def verify(self, artifact_id: str) -> bool: ...
    def lineage(self, artifact_id: str) -> dict: ...

    def load_checkpoints(
        self, task_id: str, stage_versions: dict[str, str] | None = None
    ) -> tuple[list[Any], dict[str, ArtifactBase]]: ...


class ClaimRepository(Protocol):
    def save(self, claim: FinancialClaim) -> FinancialClaim: ...
    def get(self, claim_id: str) -> FinancialClaim | None: ...
    def evidence(self, claim_id: str) -> list[str]: ...
    def claims_for_evidence(self, evidence_id: str) -> list[FinancialClaim]: ...


class VerificationJobRepository(Protocol):
    def enqueue(
        self,
        claims: list[FinancialClaim],
        provider: str = "quant",
        trace_id: str | None = None,
    ) -> list[str]: ...

    def claim_due(self, worker_id: str, limit: int, lease_seconds: int) -> list[Any]: ...
